# Generated by Django 4.1.6 on 2023-06-28 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('calorie_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_factor', models.CharField(choices=[('1', 'Little/No Exercise'), ('2', '(light exercise/sports 1-3 days per week)'), ('3', 'moderate exercise/sports 3-5 days per week'), ('4', 'hard exercise/sports 6-7 days per week'), ('5', 'very hard exercise/sports & a physical job')], max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='AddItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('food', models.CharField(max_length=70)),
                ('quantity', models.IntegerField()),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
