# Generated by Django 4.1.6 on 2023-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additems',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], default=str, max_length=40),
            preserve_default=False,
        ),
    ]
